### ISSUE TITLE
How to change the temperature style

### ISSUE THREAD

**Issue by mhonard** [potsky/Netatmo#11]
I have managed to figure out the css style sheet to change some fonts, background etc but can't figure out how to change the displayed temperature style.  Please give me some help as I am rather new at this.

**Comment by potsky** [comment]
Hi ! 

first of all, do not edit file `css/style.css` but create a new file `css/style.user.css`, it will not be erased if you update the widget by `git pull`.

In `css/style.user.css`, put these lines for example :

```
.te {
	font-size   : 20px;
	color       : #f0f!important;
}
```

Temperatures will be smaller and pink. The `important` word is "important" :-) for the color because the widget computes the color according to the temperature value. Cold is Blue and Hot is Red. If you want a static color, add `!important' next to the color in the css file.

**Comment by mhonard** [comment]
Thanks. Great program I use on  my digital sinnage.

**Comment by potsky** [comment]
Nice ! We are competitors so :-)

I am the CTO of TC Partners and we develop the VideoSpot Digital Signage solution. FYI : <https://www.videospot.com/en/>

Are you going to the ISE event?

**Comment by potsky** [comment]
Here is a old video about VideoSpot, this widget and a IR camera to detect movements :

https://www.youtube.com/watch?v=mkobEu3F7Dc
